### PR TITLE
IPython 3. Fixes #52 and #44

### LINKED ISSUE #52: Support Jupyter/IPython 3.0
Looks like 3.0 breaks support for `@manipulate`, which is a shame.

Ref: JuliaLang/IJulia.jl#224

### PR DESCRIPTION
**Pull request by shashi**
Okay after this merge, y'all can't use Interact with IPython < 2.x. Pretty much none of these changes can be elegantly hacked to preserve backward compatibility.

Since IPython 3.0 is stable and all the rage, I'm hoping that's okay. cc @jiahao @stevengj @tanmaykm

### CODE REVIEW

**Comment by Carreau** [comment]
Is there a simple thing we can do to help you having compat with precedent version ? Like detecting IPython version ? Or something else ?

**Comment by shashi** [comment]
Yeah, allowing Interact to figure out IPython version would help. But it shouldn't be decided during Pkg.build, because e.g. I have both versions in different virtualenvs but just one IJulia. This should be possible?

I am just planning to wait a week or two before tagging this so that people who are using IPython 3.0 can just do a Pkg.checkout to get the fixes for now while the current release continues to work on IPython 2.x.

**Comment by Carreau** [comment]
Getting the version from Julia Side or Js side ? 

Js Side only should be pretty easy `IPython.version` you return `X.y.z(-dev)?` on 3+, and undefined on 2.x IIRC.

**Comment by shashi** [comment]
Julia side. Yes, JS side is easy. :)

**Comment by Carreau** [comment]
OK, so I ask Jon and read [the migration doc](https://github.com/ipython/ipython/wiki/IPython-3.0-comm-and-widget-migration-document) it seam that the easiest is to send version from js side to Python side. 

I suppose once IJulia use message spec v5, you can poll IJulia for which version of the frontend you are actually talking without going through JS.

**Comment by shashi** [comment]
Yeah, I saw that doc. Alright I'll figure something out then.

**Comment by Carreau** [comment]
I guess you could shell-out to `ipython --version`, but that's not reliable.
Trying to think what to do.

**Comment by stevengj** [comment]
@shashi, it's fine to break IPython 2 compatibility in `master`, but please don't tag this in metadata until we get something figured out.  Otherwise, you will break Interact for all of the students who just managed to get IJulia installed for their work this semester.

Unfortunately, we don't have the luxury of shipping our kernel along with the IPython front-end, and the installed base of IPython 2 is huge.  It's not really acceptable to force everyone to upgrade the instant IPython 3 is released.

**Comment by shashi** [comment]
Yeah I'm holding off on tagging.

**Comment by Carreau** [comment]
So, after discussion, when you get the comm messages, you should get in the the header that tells you the message spec is v5. This should be an indication of the version of the widgets you are dealing with.

IPython-kernel-side widgets use to receive only the contents field of the massages, but now get the full message. 

That should help knowing which version of widget to use.

**Comment by stevengj** [comment]
A new version of IJulia has been tagged that requires IPython 3 or later, so it should be fine to tag Interact now if you have been holding off.

**Comment by shashi** [comment]
Tagged https://github.com/JuliaLang/METADATA.jl/pull/3337 yesterday.

I'm working on getting it to work with IPython 4, this time it's easy to make it work on both versions..

**Pull request merged**
