### PR TITLE
And ByteAbstractString

### PR DESCRIPTION
**Pull request by dpsanders**

### CODE REVIEW

**Comment by dpsanders** [comment]
Please try it out and see if it's OK ...

**Comment by shashi** [comment]
Yeah, I'm sufficiently scared now.

**Comment by dpsanders** [comment]
I've checked the original PR (#77). I believe these were the only problems.
Sorry for the noise! Note to self: check carefully before sending a PR...

**Comment by dpsanders** [comment]
Should be ready for a new tag now.

**Comment by shashi** [comment]
Actually #77 broke `Textbox` on 0.3, because `Void` there refers to `None`, I fixed it. Really, this should be automated tests...

**Comment by dpsanders** [comment]
Ouch, sorry. Yes, unit tests would be great, but I guess it's not clear how to do unit tests of interactive functionality?

**Comment by shashi** [comment]
widget constructors and things like `parse_msg` can be tested without a UI

**Pull request merged**
